baseURL: 'https://lmitelman.github.io/'
title: 'lautaromitelman.com'
theme: "PaperModX"

publishDir: "docs"
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
  #   languageName: "English"
  #   weight: 1
    taxonomies:
      category: categories
      tag: tags
    menu:
      main:
        - name: Posts
          url: /posts/
          weight: 1
        - name: Search
          url: /search/
          weight: 1
        # - name: About
        #   url: about/
        #   weight: 2
        # - name: Tags
        #   url: tags/
        #   weight: 3
        - name: Categories
          url: categories/
        #   weight: 4

outputs:
  home:
    - HTML
    - JSON

params:
  env: production
  author: lmitelman
  defaultTheme: dark
  disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  # ShowToc: true
  # comments: false
  # images: ["papermod-cover.png"]

  profileMode:
    enabled: true
    title: Lautaro Mitelman
    subtitle: >
      <span style="font-size: 1rem">_"Standing on the shoulders of giants."_</span>
      <br/>
      <br/>
    imageUrl: "https://media.licdn.com/dms/image/D4D03AQH6773SEMfAtw/profile-displayphoto-shrink_200_200/0/1710577762344?e=1727308800&v=beta&t=CR8tuPGtsAs4yUIJQkno5EzI_al-5880vUss1pgUrEI"
    imageTitle: " "
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Posts
        url: posts
      - name: Categories
        url: categories

  homeInfoParams:
    Title: "Lautaro Mitelman"
    Content: >
      <span style="font-size: 1rem">_"On the shoulders of giants."_</span>
      <br/>
      <br/>

  socialIcons:
    - name: medium
      url: "https://lmitelman.medium.com/"
    - name: twitter
      url: "https://twitter.com/LautaroMitelman"
    - name: linkedin
      url: "https://www.linkedin.com/in/lmitelman/"
    - name: github
      url: "https://github.com/lmitelman"


  #editPost:
    #URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #Text: "Suggest Changes" # edit text
    #appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
